version: '3.8'

services:
  app:
    build: .
    container_name: summarization-agent
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./tmp:/app/tmp
    env_file:
      - .env
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: summarization-agent-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: 